// See https://aka.ms/new-console-template for more information


using System.Text.Json;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json.Serialization;
using System.Security.Cryptography;
using Bitwarden.Core.API;
using System.Security;
using System.Runtime.InteropServices;
using Bitwarden.Core.Crypto;
using System.Buffers.Text;

Console.WriteLine("Hello, World!");

Test1();
//Test2();


void Test1()
{
    // https://bitwarden.com/crypto.html

    var userName = "nobody@example.com";
    var masterPassword = "p4ssw0rd";
    var iterations = 5000;

    var masterKey = BitwardenCrypto.DerriveMasterKey(masterPassword, userName, iterations);
    var masterKeyBase64 = Convert.ToBase64String(masterKey);
    var masterPasswordHash1 = BitwardenCrypto.DerriveMasterPasswordHash(masterPassword, userName, iterations);
    var masterPasswordHash2 = BitwardenCrypto.DerriveMasterPasswordHashFromMasterKey(masterKey, Encoding.ASCII.GetBytes(masterPassword));

    var stretchedmasterkey = BitwardenCrypto.StretchKey(masterKey);
    var stretchedmasterkeyBase64 = Convert.ToBase64String(stretchedmasterkey);


    // This is generated by Bitwarden on the server
    var protectedSymmetricKey = "2.CdcCLIkHMhhq0Q+Dw5RP3Q==|0GA/0NktAiCyL7UEdqOPXzVnEPVxr0r063ok+yoreNRyVc373gGw/Y5Pr8nYUfXGheX1pYoSwirWTRr7/O7uGDb6KmJQprk8QcDEm0uwQQM=|vKYPpiBmhZQooUSbegtVHxFVa2M+jwIGML7MZHDFDb4=";

    // This is the encrypted data: 1234567
    var ciptherString = "2.i1oLb5fvcnZf4Mg113bY1A==|Tt8eC5yTXLlBF0AKDNwkIw==|nQ+bec9UNDVGdJgtYZXYYQHDhmNagE79jxEWqsDnA+s=";

    var unprotectedSymmetricKey0 = BitwardenCrypto.DecryptEncryptionKey(protectedSymmetricKey, masterKey);
    var unprotectedSymmetricKey0Base64 = Convert.ToBase64String(unprotectedSymmetricKey0);
    var plainText0 = BitwardenCrypto.DecryptEntry(ciptherString, unprotectedSymmetricKey0, true);


    var unprotectedSymmetricKey1 = BitwardenCrypto.DecryptEncryptionKey("2.uKntnrd31vxE2XptUOEJDw==|Bgtw3NbARqEvLGZhw4b0+oHUbO8s8KvGI7ISRj/HUpZd/pUyYwM03taCIXFgweOuf5TeS0shuya/L1XLpkkB24PPzd/SKVhwMD9E4XT8F6A=|VHOabQCGcZQiL9o5hWaoEp+ZxaHdIYGNPiNNjf6bakE=", masterKey);
    var unprotectedSymmetricKey1Base64 = Convert.ToBase64String(unprotectedSymmetricKey1);
    var plainText1 = BitwardenCrypto.DecryptEntry("2.1AALNIzzJor78bXpaQx1yw==|RBcOhPyFjew5J5kAm/a6kA==|TeFpTR+tppU2qFdM6gDUjgaqx57N8MxRzzp+IU/EYZg=", unprotectedSymmetricKey1, true);




    //var encryptionKey1 = BitwardenCrypto.DecryptEncryptionKey("2.uKntnrd31vxE2XptUOEJDw==|Bgtw3NbARqEvLGZhw4b0+oHUbO8s8KvGI7ISRj/HUpZd/pUyYwM03taCIXFgweOuf5TeS0shuya/L1XLpkkB24PPzd/SKVhwMD9E4XT8F6A=|VHOabQCGcZQiL9o5hWaoEp+ZxaHdIYGNPiNNjf6bakE=", masterKey);
    //var plainText1 = BitwardenCrypto.DecryptEntry("2.1AALNIzzJor78bXpaQx1yw==|RBcOhPyFjew5J5kAm/a6kA==|TeFpTR+tppU2qFdM6gDUjgaqx57N8MxRzzp+IU/EYZg=", encryptionKey1, true);

    //// r5CFRR+n9NQI8a525FY+0BPR0HGOjVJX0cR1KEMnIOo=
    //var encryptionKey2 = BitwardenCrypto.DecryptEncryptionKey("0.uRcMe+Mc2nmOet4yWx9BwA==|PGQhpYUlTUq/vBEDj1KOHVMlTIH1eecMl0j80+Zu0VRVfFa7X/MWKdVM6OM/NfSZicFEwaLWqpyBlOrBXhR+trkX/dPRnfwJD2B93hnLNGQ=", masterKey);
    //var plainText2 = BitwardenCrypto.DecryptEntry("2.6DmdNKlm3a+9k/5DFg+pTg==|7q1Arwz/ZfKEx+fksV3yo0HMQdypHJvyiix6hzgF3gY=|7lSXqjfq5rD3/3ofNZVpgv1ags696B2XXJryiGjDZvk=", encryptionKey2, true);


}

void Test2()
{
    JsonSerializerOptions serializerOptions = new JsonSerializerOptions()
    { WriteIndented = true, Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    var dataPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), DesktopConstants.DefaultDataFolderName);
    var fileName = "settings.json";
    var fullPath = Path.Combine(dataPath, fileName);


    var json = File.ReadAllText(fullPath, Encoding.UTF8);
    var bitwardenClientConfiguration = default(BitwardenClientConfiguration);
    if (JsonSerializer.Deserialize<Settings>(json, serializerOptions) is Settings t)
    {
        bitwardenClientConfiguration = t.BitwardenClientConfiguration;
    }
    else
    {
        throw new Exception("Unable to load instance from file");
    }


    var baseAddesss = bitwardenClientConfiguration.base_address;
    var email = bitwardenClientConfiguration.email;
    var clientID = bitwardenClientConfiguration.client_id;
    var clientSecret = bitwardenClientConfiguration.client_secret;
    var deviceName = bitwardenClientConfiguration.device_name;
    var deviceIdentifier = bitwardenClientConfiguration.device_identifier;
    var userName = email;
    var password = bitwardenClientConfiguration.master_key; //password -> PBKDF2 10,000 iterations -> master key
    var twoFactorToken = "123456";



    Console.WriteLine("Enter master password");
    var masterPassword = GetPassword().ToUnsecureString();
    var masterKey = BitwardenCrypto.DerriveMasterKey(masterPassword, userName, 10000);
    var masterKeyBase64 = Convert.ToBase64String(masterKey);


    var preLogin = BitwardenProtocol.GetPreLogin(baseAddesss, email).GetAwaiter().GetResult();

    var x = preLogin;



}













static SecureString GetPassword()
{
    var pwd = new SecureString();
    while (true)
    {
        ConsoleKeyInfo i = Console.ReadKey(true);
        if (i.Key == ConsoleKey.Enter)
        {
            break;
        }
        else if (i.Key == ConsoleKey.Backspace)
        {
            if (pwd.Length > 0)
            {
                pwd.RemoveAt(pwd.Length - 1);
                Console.Write("\b \b");
            }
        }
        else if (i.KeyChar != '\u0000') // KeyChar == '\u0000' if the key pressed does not correspond to a printable character, e.g. F1, Pause-Break, etc
        {
            pwd.AppendChar(i.KeyChar);
            Console.Write("*");
        }
    }
    return pwd;


}

static class Helpers
{
    public static string ToUnsecureString(this SecureString secureString)
    {
        if (secureString == null) return null;
        var unmanagedString = IntPtr.Zero;
        try
        {
            unmanagedString = Marshal.SecureStringToGlobalAllocUnicode(secureString);
            return Marshal.PtrToStringUni(unmanagedString);
        }
        finally
        {
            Marshal.ZeroFreeGlobalAllocUnicode(unmanagedString);
        }
    }
}


public class BitwardenClientConfiguration : IBitwardenClientConfiguration
{
    [JsonConverter(typeof(ProtectedDataConverter))] public string? base_address { get; set; }
    [JsonConverter(typeof(ProtectedDataConverter))] public string? email { get; set; }
    [JsonConverter(typeof(ProtectedDataConverter))] public string? master_key { get; set; }
    [JsonConverter(typeof(ProtectedDataConverter))] public string? client_id { get; set; }
    [JsonConverter(typeof(ProtectedDataConverter))] public string? client_secret { get; set; }
    [JsonConverter(typeof(ProtectedDataConverter))] public string? refresh_token { get; set; }
    [JsonConverter(typeof(ProtectedDataConverter))] public string? device_name { get; set; }
    [JsonConverter(typeof(ProtectedDataConverter))] public string? device_identifier { get; set; }
}

public interface IBitwardenClientConfiguration
{
    string? base_address { get; set; }
    string? client_id { get; set; }
    string? client_secret { get; set; }
    string? device_identifier { get; set; }
    string? device_name { get; set; }
    string? email { get; set; }
    string? master_key { get; set; }
    string? refresh_token { get; set; }
}

public class DefaultBitwardenClientConfiguration : IBitwardenClientConfiguration
{
    public string? base_address { get; set; }
    public string? email { get; set; }
    public string? master_key { get; set; }
    public string? client_id { get; set; }
    public string? client_secret { get; set; }
    public string? refresh_token { get; set; }
    public string? device_name { get; set; }
    public string? device_identifier { get; set; }
}

public class Settings
{
    public BitwardenClientConfiguration? BitwardenClientConfiguration { get; set; } = new BitwardenClientConfiguration();
}
public static class DesktopConstants
{
    public static readonly string DefaultDataFolderName = "BitwardenAutoType";
}


public class ProtectedDataConverter : JsonConverter<string?>
{
    public static readonly string Key = "<Protected>";
    public static readonly byte[] Entropy = new byte[] { 77, 54, 8, 44, 1 };

    public override string? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        if (value is null ||
            value.Length < Key.Length ||
            !value.StartsWith(Key))
        {
            return value;
        }

        var base64 = String.Concat(value.Skip(Key.Length));
        var binary = Convert.FromBase64String(base64);
        var data = ProtectedData.Unprotect(binary, Entropy, DataProtectionScope.CurrentUser);
        return Encoding.ASCII.GetString(data);
    }

    public override void Write(Utf8JsonWriter writer, string? value, JsonSerializerOptions options)
    {
        if (writer is null) return;
        var plainText = value!.ToString();
        if (plainText.Length == 0)
        {
            writer.WriteStringValue(string.Empty);
            return;
        }

        var plainBytes = Encoding.ASCII.GetBytes(plainText);
        var encryptedBytes = ProtectedData.Protect(plainBytes, Entropy, DataProtectionScope.CurrentUser);
        var encryptedBytesBase64 = $"{Key}{Convert.ToBase64String(encryptedBytes)}";
        writer.WriteStringValue(encryptedBytesBase64);
    }
}